language: clojure
dist: trusty
sudo: true
branches:
  only:
  - master
before_install: bash etc/ci-setup.sh
install: true
script: eval "$TEST_CMD"
after_script: heroku keys:remove $USER@`hostname`
env:
  global:
  - IS_RUNNING_ON_TRAVIS=true
  - HATCHET_RETRIES=3
  - HATCHET_DEPLOY_STRATEGY=git
  - HATCHET_BUILDPACK_BASE="https://github.com/heroku/heroku-buildpack-clojure.git"
  - SHUNIT_HOME="/tmp/shunit2-2.1.6"
  matrix:
  - TEST_CMD="/tmp/testrunner/bin/run -c ."
  - TEST_CMD="bash etc/hatchet-test.sh"
